### ISSUE TITLE
Fails to generate a TEMP in HM3 mode, seemingly at random

### ISSUE THREAD

**Issue by atampy25** [OrfeasZ/ZHMTools#9]
ResourceTool fails to generate a TEMP from a TEMP.json file, seemingly at random.

Simple Mod Framework output when it fails:
```
DEBUG   Converting entity C:\Users\User\Documents\Apps\Games\Epic Games\HITMAN3\Mod Framework\Mods\Zen Garden\content\chunk1\ZenGarden.entity.json
ERROR   Unhandled promise rejection! Error: Command failed: "Third-Party\ResourceTool.exe" HM3 generate TEMP "C:\Users\User\Documents\Apps\Games\Epic Games\HITMAN3\Mod Framework\temp\temp.TEMP.json" "C:\Users\User\Documents\Apps\Games\Epic Games\HITMAN3\Mod Framework\temp\temp.TEMP" --simple
Trace
    at Object.error (C:\snapshot\simple-mod-framework\main.js:55:11)
    at process.<anonymous> (C:\snapshot\simple-mod-framework\main.js:80:9)
Promise {
  <rejected> Error: Command failed: "Third-Party\ResourceTool.exe" HM3 generate TEMP "C:\Users\User\Documents\Apps\Games\Epic Games\HITMAN3\Mod Framework\temp\temp.TEMP.json" "C:\Users\User\Documents\Apps\Games\Epic Games\HITMAN3\Mod Framework\temp\temp.TEMP" --simple
      at stageAllMods (C:\snapshot\simple-mod-framework\main.js:329:23) {
    status: 3221225477,
    signal: null,
    output: [ null, <Buffer >, <Buffer > ],
    pid: 34960,
    stdout: <Buffer >,
    stderr: <Buffer >
  }
}
```

Event viewer output:
```
Faulting application name: ResourceTool.exe, version: 0.0.0.0, time stamp: 0x61e9b60e
Faulting module name: ResourceLib_HM3.dll, version: 0.0.0.0, time stamp: 0x61e9b592
Exception code: 0xc0000005
Fault offset: 0x00000000002e8a1b
Faulting process ID: 0x4110
Faulting application start time: 0x01d80e819de7e6a3
Faulting application path: C:\Users\User\Documents\Apps\Games\Epic Games\HITMAN3\Mod Framework\Third-Party\ResourceTool.exe
Faulting module path: C:\Users\User\Documents\Apps\Games\Epic Games\HITMAN3\Mod Framework\Third-Party\ResourceLib_HM3.dll
Report ID: ab237850-0658-4c9a-b652-7d880bfe52cc
Faulting package full name: 
Faulting package-relative application ID: 
```

No data is output to stdout or stderr when this happens, and the TEMP file is not created.

The issue occasionally does not occur it seems, with the framework successfully deploying and the command still returning nothing.

**Comment by atampy25** [comment]
I think this was fixed in one of the updates since v3.0.0; I don't remember which
